const dataweb = [
    {
        "id": 1,
        "titulo": "Conoce Como Utilizar CRM para Retener y Fidelizar Clientes.",
        "urlImage": "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva1.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva2.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva3.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva4.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva5.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva6.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva7.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva8.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva9.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva10.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva11.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva12.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva13.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva14.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva15.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva16.webp",
            "/img/Web/htmlCSsJs/Mockup_Conoce_Como_Utilizar_CRM_Para_Retener__y_Fidelizar_Clientes/Diapositiva17.webp"
        ]
    },
    {
        "id": 2,
        "titulo": " Cree  su  Plan  de  Comunicación  Digital. ",
        "urlImage": "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva1.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva2.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva3.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva4.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva5.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva6.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva7.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva8.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva9.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva10.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva11.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva12.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva13.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva14.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva15.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva16.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva17.webp",
            "/img/Web/htmlCSsJs/Mockup_Cree_su_Plan_de _Comunicacion/Diapositiva18.webp" ]
    },
    {
        "id": 3,
        "titulo": " Maneje Eficientemente sus Inventarios através de la Sistematización.",
        "urlImage": "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva1.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva2.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva3.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva4.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva5.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva6.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva7.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva8.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva9.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva10.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva11.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva12.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva13.webp",
            "/img/Web/htmlCSsJs/Mockup_Maneje_Eficientemente_sus_Invetarios/Diapositiva14.webp"
        ]
    },
    {
        "id": 4,
        "titulo": "Conozca los Beneficios de Contar con sus Inventarios Automatizados.",
        "urlImage": "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva1.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva2.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva3.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva4.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva5.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva6.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva7.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva8.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva9.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva10.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva11.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva12.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva13.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva14.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva15.webp",
            "/img/Web/htmlCSsJs/Mockup_Conozca_las_Herramientas_y Los_Beneficios_de_Contar_con_sus_Inventarios_Automatizados/Diapositiva16.webp"
        ]
    },
    {
        "id": 5,
        "titulo": "Pontencializa el Uso del CRM en tu Empresa.",
        "urlImage": "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva1.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva2.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva3.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva4.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva5.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva6.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva7.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva8.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva9.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva10.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva11.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva12.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva13.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva14.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva15.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva16.webp",
            "/img/Web/htmlCSsJs/Mockup_Potencializa_el_Uso_del_CRM/Diapositiva17.webp"
        ]
    },
    {
        "id": 6,
        "titulo": "Preste sus Servicios de Forma Automatizada.",
        "urlImage": "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva1.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva2.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva3.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva4.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva5.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva6.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva7.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva8.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva9.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva10.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva11.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva12.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva13.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva14.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva15.webp",
            "/img/Web/htmlCSsJs/Mockup_Preste_sus_Servicios_de_Forma_Automatizada/Diapositiva16.webp"
        ]
    },
    {
        "id": 7,
        "titulo": "Como darle Notoriedad a su Marca con el Branded Content.",
        "urlImage": "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva1.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva2.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva3.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva4.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva5.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva6.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva7.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva8.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva9.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva10.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva11.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva12.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva13.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva14.webp",
            "/img/Web/storeLine/Mockup_Branded_Content/Diapositiva15.webp"
        ]
    },
    {
        "id": 8,
        "titulo": "Como Hacer Contratos con sus Clientes y Proveedores.",
        "urlImage": "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva1.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva2.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva3.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva4.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva5.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva6.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva7.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva8.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva9.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva10.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva11.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva12.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva13.webp",
            "/img/Web/storeLine/Mockup_Como_Hacer_Contratos_con_sus_Clientes _y_Provedores/Diapositiva14.webp"
        ]
    },
    {
        "id": 9,
        "titulo": "Conoce los Beneficios para Ser una Sociedad BIC.",
        "urlImage": "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva1.webp",
        "descripcion": "Este proyecto es un curso virtual que esta realizado para la <strong>Cámara de Comercio de Bogotá</strong> por medio de la empresa <strong>Virtual Technologies S.A.S</strong>.",
        "galeria": [
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva1.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva2.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva3.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva4.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva5.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva6.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva7.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva8.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva9.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva10.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva11.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva12.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva13.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva14.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva15.webp",
            "/img/Web/storeLine/Mockup_Conoce_los_Beneficios_para_Ser_una_Sociedad_BIC/Diapositiva16.webp"
        ]
    },
    {
        "id": 10,
        "titulo": "A un clic del cambio.",
        "urlImage": "/img/Web/backend/a_un_clic_del_cambio/Diapositiva1.webp",
        "descripcion": "Este proyecto es realizado en el BACKEND que consiste en la orquestación de CI/CD usando tecnologías como Jenkins, AWS, GitHub Actions y Docker con una app de React <strong> <a target='_blank' href='https://pinnate-wood-e69.notion.site/A-un-clic-del-cambio-por-Carlos-Aristizabal-e0ee9b3136f54fd6a01e45b222ca44f3'>para leer más en la documentación</a></strong>",
        "galeria": [
            "/img/Web/backend/a_un_clic_del_cambio/Diapositiva1.webp",
            "/img/Web/backend/a_un_clic_del_cambio/Diapositiva2.webp",
            "/img/Web/backend/a_un_clic_del_cambio/Diapositiva3.webp",
        ]

    }

]

export default dataweb